import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {planConstruction,packageFingerprint,recordConstructionConclusions,constructionConclusion,rememberConstructionCheck} from '../packages/nexogenesis-tools/lib/uno/construction-plan.js';
import {unoMarkdown,unoRevision} from '../packages/nexogenesis-tools/lib/harness/uno-storage.js';
import {runConstructionTool} from '../packages/nexogenesis-tools/lib/uno/construction-workflow.js';
import {saveCompileJob} from '../packages/nexogenesis-tools/lib/uno/state.js';
import {constructReviewPending} from '../packages/nexogenesis-tools/lib/uno/recovery.js';
import {initializeProviderBudget} from '../packages/nexogenesis-tools/lib/uno/request-budget.js';
import {publicationGroups} from '../packages/nexogenesis-web-host/lib/construction-host.js';
import {invalidateKnowledgeSnapshot} from '../packages/nexogenesis-tools/lib/cards.js';

function fixture(t){const root=mkdtempSync(join(tmpdir(),'uno-direction-'));t.after(()=>rmSync(root,{recursive:true,force:true}));mkdirSync(join(root,'01-Cards'));mkdirSync(join(root,'03-Archive'));writeFileSync(join(root,'03-Archive/source.md'),'市场竞争的边界。');
 const add=(id,title='市场竞争的边界')=>writeFileSync(join(root,'01-Cards',id+'.md'),unoMarkdown({schema:'uno-card-v4',id,title,summary:title,type:'claim',domains:[],sources:['03-Archive/source.md'],boundary:'限于当前材料',lifecycle:'active'},`${title}。甲作者在限定条件下提出，乙作者不同意这一判断。`));
 add('a');add('b','市场竞争的反例');add('z','天文学历史');
 const input={notes:'市场竞争的反例和观点分歧',card_ids:['a','b']};const plan=planConstruction(root,input),job={id:'direction',workflow:'uno-compile-v3',orchestration_profile:'bounded-workflow-v1',construction_profile:'direction-driven-v1',mode:'construct',construct_contract:'scoped-review-v1',construction_plan:plan,batches:plan.packages.map(p=>p.card_ids),scope:['a','b'],batch_index:0,phase:'read',role:'author',status:'running',session_id:'s',calls:[],budget:{calls:10},receipts:[],touched:[],issues:[],failures:[],sources:[],requirements:{preferences:{delivery:'auto'}}};
 saveCompileJob(root,job);initializeProviderBudget(root,job.id,{limit:10});return {root,add,input,job};}

test('direction selects related comparison groups without manual ids; unselected remains explicit',t=>{const f=fixture(t);const p=planConstruction(f.root,{notes:'市场竞争的反例'});assert.ok(p.packages[0].card_ids.includes('a'));assert.ok(p.packages[0].card_ids.includes('b'));assert.ok(p.unselected.includes('z'));assert.match(p.packages[0].reason,/相似不等于重复/);assert.throws(()=>planConstruction(f.root,{notes:' '}),/方向/);});
test('unchanged needs current full reading and differs from deferred and source verified',t=>{const f=fixture(t);assert.throws(()=>recordConstructionConclusions(f.root,f.job,[{id:'a',status:'unchanged',note:'保留作者分歧。'}]),/未完整/);
 runConstructionTool(f.root,f.job,'compile_read_card',{id:'a'});recordConstructionConclusions(f.root,f.job,[{id:'a',status:'unchanged',note:'保留作者分歧。'},{id:'b',status:'deferred',note:'还需核对来源条件。'}]);
 assert.equal(constructionConclusion(f.root,f.job,'a').source_verified,false);assert.deepEqual(constructReviewPending(f.root,f.job).map(r=>r.id),['b']);
 f.add('a','市场竞争新增主张');assert.equal(constructionConclusion(f.root,f.job,'a'),null);});
test('incremental reuse requires same goal, versions, sources, neighbors, inventory and rules; force bypasses',t=>{const f=fixture(t);
 for(const id of ['a','b'])runConstructionTool(f.root,f.job,'compile_read_card',{id});
 recordConstructionConclusions(f.root,f.job,['a','b'].map(id=>({id,status:'unchanged',note:'已读当前正文，作者和边界不同，保留独立对象。'})));rememberConstructionCheck(f.root,f.job,0);
 assert.equal(planConstruction(f.root,f.input).skipped.length,1);assert.equal(planConstruction(f.root,{...f.input,force_recheck:true}).skipped.length,0);
 assert.equal(planConstruction(f.root,{...f.input,notes:'市场竞争的事实核验'}).skipped.length,0);
 const previous=packageFingerprint(f.root,f.job.construction_plan,f.job.construction_plan.packages[0]);writeFileSync(join(f.root,'03-Archive/source.md'),'来源修正了先前条件。');
 assert.notEqual(packageFingerprint(f.root,f.job.construction_plan,f.job.construction_plan.packages[0]),previous);assert.equal(planConstruction(f.root,f.input).skipped.length,0);
});
test('deferred and fact audits cannot enter the no-change cache',t=>{const f=fixture(t);recordConstructionConclusions(f.root,f.job,['a','b'].map(id=>({id,status:'deferred',note:'未核验。'})));rememberConstructionCheck(f.root,f.job,0);assert.equal(planConstruction(f.root,f.input).skipped.length,0);
 f.job.construction_plan.kind='factual-audit';for(const id of ['a','b'])runConstructionTool(f.root,f.job,'compile_read_card',{id});recordConstructionConclusions(f.root,f.job,['a','b'].map(id=>({id,status:'unchanged',note:'卡正文已读，未独立核验事实。'})));assert.equal(constructReviewPending(f.root,f.job).length,2);});
test('existing relation target does not couple unrelated rejected draft; new targets and pinned drafts do',()=>{
 const drafts=[{card:{id:'a',relations:[{target:'b'}]}},{card:{id:'b',relations:[]}}];
 assert.deepEqual(publicationGroups(drafts,new Set(['a','b'])),[['a'],['b']]);
 assert.deepEqual(publicationGroups(drafts,new Set(['a'])),[['a','b'],['b']]);
 assert.deepEqual(publicationGroups(drafts,new Set(['a','b']),{a:{dependencies:[{id:'b',draft:true}]}}),[['a','b'],['b']]);
});
test('stable Buffer index cannot hide changed underlying source from incremental checks',t=>{const f=fixture(t);
 mkdirSync(join(f.root,'05-Buffer/_index'),{recursive:true});mkdirSync(join(f.root,'05-Buffer/topic'),{recursive:true});
 const index='05-Buffer/_index/unit.md',physical='05-Buffer/topic/unit.md';
 writeFileSync(join(f.root,index),unoMarkdown({kind:'uno-material-index',unit_id:'u',target:physical},''));
 writeFileSync(join(f.root,physical),unoMarkdown({kind:'uno-raw-v3',unit_id:'u'},'原始判断支持甲。'));
 const path=join(f.root,'01-Cards/a.md');writeFileSync(path,readFileSync(path,'utf8').replace('03-Archive/source.md',index));invalidateKnowledgeSnapshot(f.root);
 const p=planConstruction(f.root,f.input),before=packageFingerprint(f.root,p,p.packages[0]);
 writeFileSync(join(f.root,physical),unoMarkdown({kind:'uno-raw-v3',unit_id:'u'},'更正判断不支持甲。'));
 assert.notEqual(packageFingerprint(f.root,p,p.packages[0]),before);
});
test('retirement redirects stay valid dependencies, including the active destination version',t=>{const f=fixture(t);
 const a=join(f.root,'01-Cards/a.md');writeFileSync(a,readFileSync(a,'utf8').replace('lifecycle: active','relations: [{target: old-b, type: contrast, note: 同一问题的另一种解释}]\nlifecycle: active'));
 writeFileSync(join(f.root,'01-Cards/old-b.md'),unoMarkdown({id:'old-b',title:'旧对象',lifecycle:'superseded',superseded_by:'b'},'历史正文'));
 invalidateKnowledgeSnapshot(f.root);
 runConstructionTool(f.root,f.job,'compile_read_card',{id:'a'});recordConstructionConclusions(f.root,f.job,[{id:'a',status:'unchanged',note:'已核对当前卡片，旧关系仍可沿去向找到有效承载对象。'}]);
 assert.equal(constructionConclusion(f.root,f.job,'a').status,'unchanged');f.add('b','新条件');assert.equal(constructionConclusion(f.root,f.job,'a'),null);
});
test('an existing source file with a missing anchor cannot become an unchanged conclusion',t=>{const f=fixture(t),path=join(f.root,'01-Cards/a.md');
 writeFileSync(path,readFileSync(path,'utf8').replace('03-Archive/source.md','03-Archive/source.md#missing'));
 invalidateKnowledgeSnapshot(f.root);
 runConstructionTool(f.root,f.job,'compile_read_card',{id:'a'});
 assert.throws(()=>recordConstructionConclusions(f.root,f.job,[{id:'a',status:'unchanged',note:'保留。'}]),/来源或关系端点缺失/);
});
